name: EFP CI

on: 
  push:
    branches: 
    - master
    - release/*
    - fix/*
  pull_request: 
    branches: 
    - master
    - fix/* 

jobs:
  # greetings: 
  #   runs-on: ubuntu-latest
  #   steps: 
  #   - uses: actions/first-interaction@v1
  #     with: 
  #       repo-token: ${{ secrets.TOKEN }}
  #       issue-message: 'Thanks for your first contribution issue towards this repo'  'First Issue'
  #       pr-message: 'Thanks for your first contributions towards this repo' 'PR Message' 
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install 
    - name: npm lint
      run: npm run lint
  build: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - name: Build Docker image 
      run: docker build . --file Dockerfile --tag gitaction
  docker_login: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/docker/login@master 
      env: 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  publish: 
    needs: docker_login
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        node: [6, 8, 10]
        os: [ubuntu-16.04, ubuntu-18.04]
    steps:
    - uses: elgohr/Publish-Docker-Github-Action@master
    - name: Publish to reg
      with: 
        args: yogeshvar/efp
      
